version: '3.3'

services:

  beestorage:
    image: lionants02/thumbormongodocker:1.3
    environment:
      - MONGO_STORAGE_SERVER_HOST=11.0.0.164
      - MONGO_STORAGE_SERVER_PORT=27081
      - MONGO_STORAGE_SERVER_DB=picture
      - MONGO_STORAGE_SERVER_COLLECTION=imagefile
      - UPLOAD_ENABLED=True
      - UPLOAD_PUT_ALLOWED=True
      - UPLOAD_DELETE_ALLOWED=True
      - STORAGE_EXPIRATION_SECONDS=2592000
      - MAX_WIDTH=0
      - MAX_HEIGHT=0
      - UPLOAD_MAX_SIZE=0
      - MAX_AGE=0
    ports:
      - "9000:8000"
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure


  mongo_router:
    image: mongo:3.4
    ports:
      - "27081:27081"
    volumes:
      - database/router/db:/data/db
      - database/router/configdb:/data/configdb
    command: sh -c 'su --command "mongos --configdb configserver/11.0.0.164:27019 --port 27081"'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.role == router1
    depends_on:
      - configdb_r1s1
      - datadb_r1s1

  configdb_r1s1:
    image: mongo:3.4
    volumes:
      - database/configdb:/data/configdb
    ports:
      - "27019:27019"
    command: mongod --configsvr --smallfiles --replSet configserver --port 27019
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.role == router1

  datadb_r1s1:
    image: mongo:3.4
    volumes:
      - database/db:/data/db
    ports:
      - "27020:27020"
    command: mongod --noprealloc --replSet dataGroup1 --shardsvr --port 27020
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.role == shard1n1
