version: '3'
services:

  router1:
    build: ./router
    command: sh -c 'sleep 5 && su --command "sh /data/init.sh &" && sleep 5 && su --command "mongos --configdb configserver/config1:27019 --port 27081"'
    ports:
    - "27081:27081"
    depends_on:
      - config1
      - shard1n1
      - shard2n1

  config1:
    image: mongo:3.4
    restart: on-failure
    tmpfs: /data/configdb
    command: mongod --configsvr --smallfiles --replSet configserver --port 27019

  shard1n1:
    image: mongo:3.4
    restart: on-failure
    ports:
      - "8001:27020"
    command: mongod --noprealloc --replSet dataGroup1 --shardsvr --port 27020

  shard2n1:
    image: mongo:3.4
    restart: on-failure
    ports:
      - "8003:27020"
    command: mongod --noprealloc --replSet dataGroup2 --shardsvr --port 27020
