version: '3'
services:

  thumbor:
    image: lionants02/thumbormongodocker
    environment:
      - MONGO_STORAGE_SERVER_HOST=router1
      - MONGO_STORAGE_SERVER_PORT=27081
      - MONGO_STORAGE_SERVER_DB=picture
      - MONGO_STORAGE_SERVER_COLLECTION=imagefile
      - UPLOAD_ENABLED=True
      - UPLOAD_PUT_ALLOWED=True
    ports:
    - "8000:8000"
    depends_on:
      - router1

  router1:
    build: ./router
    ports:
    - "27081:27081"
    depends_on:
      - config1
      - config2
      - shard1
      - shard2
      - shard3

  config1:
    image: mongo:3.4
    command: mongod --configsvr --replSet configserver --port 27019

  config2:
    image: mongo:3.4
    command: mongod --configsvr --replSet configserver --port 27019

  shard1:
    image: mongo:3.4
    command: mongod --shardsvr --port 27020

  shard2:
    image: mongo:3.4
    command: mongod --shardsvr --port 27020

  shard3:
    image: mongo:3.4
    command: mongod --shardsvr --port 27020
