version: '3'
services:

  nginx:
    build: ./nginxBalance
    ports:
    - "7000:80"
    depends_on:
      - thumbor1
      - thumbor2
      - thumbor3

  thumbor1:
    image: lionants02/thumbormongodocker
    environment:
      - MONGO_STORAGE_SERVER_HOST=router1
      - MONGO_STORAGE_SERVER_PORT=27081
      - MONGO_STORAGE_SERVER_DB=picture
      - MONGO_STORAGE_SERVER_COLLECTION=imagefile
      - UPLOAD_ENABLED=True
      - UPLOAD_PUT_ALLOWED=True
      - MAX_WIDTH=0
      - MAX_HEIGHT=0
      - UPLOAD_MAX_SIZE=0
    ports:
    - "8000:8000"
    restart: on-failure
    depends_on:
      - router1

  thumbor2:
    image: lionants02/thumbormongodocker
    environment:
      - MONGO_STORAGE_SERVER_HOST=router1
      - MONGO_STORAGE_SERVER_PORT=27081
      - MONGO_STORAGE_SERVER_DB=picture
      - MONGO_STORAGE_SERVER_COLLECTION=imagefile
      - UPLOAD_ENABLED=True
      - UPLOAD_PUT_ALLOWED=True
      - MAX_WIDTH=0
      - MAX_HEIGHT=0
      - UPLOAD_MAX_SIZE=0
    restart: on-failure
    depends_on:
      - router1

  thumbor3:
    image: lionants02/thumbormongodocker
    environment:
      - MONGO_STORAGE_SERVER_HOST=router1
      - MONGO_STORAGE_SERVER_PORT=27081
      - MONGO_STORAGE_SERVER_DB=picture
      - MONGO_STORAGE_SERVER_COLLECTION=imagefile
      - UPLOAD_ENABLED=True
      - UPLOAD_PUT_ALLOWED=True
      - MAX_WIDTH=0
      - MAX_HEIGHT=0
      - UPLOAD_MAX_SIZE=0
    restart: on-failure
    depends_on:
      - router1


  router1:
    build: ./router
    ports:
      - "27081:27081"
    command: sh -c 'sleep 5 && su --command "sh /data/init.sh &" && sleep 5 && su --command "mongos --configdb configserver/shard1n1:27019,shard1n2:27019,shard2n1:27019,shard2n2:27019,shard3n1:27019,shard3n2:27019 --port 27081"'
    depends_on:
      - shard1n1
      - shard1n2
      - shard2n1
      - shard2n2
      - shard3n1
      - shard3n2

  shard1n1:
    image: mongo:3.4
    restart: on-failure
    tmpfs: /data/configdb
    ports:
      - "8001:27020"
    command: sh -c 'su --command "mongod --noprealloc --replSet dataGroup1 --shardsvr --port 27020 &" && su --command "mongod --configsvr --smallfiles --replSet configserver --port 27019"'

  shard1n2:
    image: mongo:3.4
    restart: on-failure
    tmpfs: /data/configdb
    ports:
      - "8002:27020"
    command: sh -c 'su --command "mongod --noprealloc --replSet dataGroup1 --shardsvr --port 27020 &" && su --command "mongod --configsvr --smallfiles --replSet configserver --port 27019"'

  shard2n1:
    image: mongo:3.4
    restart: on-failure
    tmpfs: /data/configdb
    ports:
      - "8003:27020"
    command: sh -c 'su --command "mongod --noprealloc --replSet dataGroup2 --shardsvr --port 27020 &" && su --command "mongod --configsvr --smallfiles --replSet configserver --port 27019"'

  shard2n2:
    image: mongo:3.4
    restart: on-failure
    tmpfs: /data/configdb
    ports:
      - "8004:27020"
    command: sh -c 'su --command "mongod --noprealloc --replSet dataGroup2 --shardsvr --port 27020 &" && su --command "mongod --configsvr --smallfiles --replSet configserver --port 27019"'

  shard3n1:
    image: mongo:3.4
    restart: on-failure
    tmpfs: /data/configdb
    ports:
      - "8005:27020"
    command: sh -c 'su --command "mongod --noprealloc --replSet dataGroup3 --shardsvr --port 27020 &" && su --command "mongod --configsvr --smallfiles --replSet configserver --port 27019"'

  shard3n2:
    image: mongo:3.4
    restart: on-failure
    tmpfs: /data/configdb
    ports:
      - "8006:27020"
    command: sh -c 'su --command "mongod --noprealloc --replSet dataGroup3 --shardsvr --port 27020 &" && su --command "mongod --configsvr --smallfiles --replSet configserver --port 27019"'
