version: '3'
services:

  nginx:
    build: ./nginxBalance
    ports:
    - "7000:80"
    depends_on:
      - thumbor1

  thumbor1:
    image: lionants02/thumbormongodocker:1.3
    environment:
      - MONGO_STORAGE_SERVER_HOST=router1
      - MONGO_STORAGE_SERVER_PORT=27081
      - MONGO_STORAGE_SERVER_DB=picture
      - MONGO_STORAGE_SERVER_COLLECTION=imagefile
      - UPLOAD_ENABLED=True
      - UPLOAD_PUT_ALLOWED=True
      - UPLOAD_DELETE_ALLOWED=True
      - STORAGE_EXPIRATION_SECONDS=2592000
      - MAX_WIDTH=0
      - MAX_HEIGHT=0
      - UPLOAD_MAX_SIZE=0
      - MAX_AGE=0
    ports:
    - "8000:8000"
    restart: on-failure
    depends_on:
      - router1


  router1:
    build: ./router
    command: sh -c 'sleep 5 && su --command "sh /data/init.sh &" && sleep 5 && su --command "mongos --configdb configserver/config1:27019 --port 27081"'
    ports:
    - "27081:27081"
    depends_on:
      - config1
      - shard1n1
      - shard2n1

  config1:
    image: mongo:3.4
    restart: on-failure
    tmpfs: /data/configdb
    command: mongod --configsvr --smallfiles --replSet configserver --port 27019

  shard1n1:
    image: mongo:3.4
    restart: on-failure
    ports:
      - "8001:27020"
    command: mongod --noprealloc --replSet dataGroup1 --shardsvr --port 27020

  shard2n1:
    image: mongo:3.4
    restart: on-failure
    ports:
      - "8003:27020"
    command: mongod --noprealloc --replSet dataGroup2 --shardsvr --port 27020
