version: '3.3'

services:

  router1:
    image: mongo:3.4
    ports:
      - "27081:27081"
    volumes:
      - /mnt/beestorage-swarm/database/router/db:/data/db
      - /mnt/beestorage-swarm/database/router/configdb:/data/configdb
    command: sh -c 'su --command "mongos --configdb configserver/11.0.0.164:27019 --port 27081"'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.role == router1
    depends_on:
      - config1
      - shard1n1

  config1:
    image: mongo:3.4
    volumes:
      - /mnt/beestorage-swarm/database/configdb:/data/configdb
    ports:
      - "27019:27019"
    command: mongod --configsvr --smallfiles --replSet configserver --port 27019
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.role == router1

  shard1n1:
    image: mongo:3.4
    volumes:
      - /mnt/beestorage-swarm/database/db:/data/db
    ports:
      - "27020:27020"
    command: mongod --noprealloc --replSet dataGroup1 --shardsvr --port 27020
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.role == shard1n1
