version: '3.3'

networks:
  mongoIMG:
    external: true
  thumborapi:
    external: true


services:

  nginx:
    image: nginx:latest
    volumes:
       - /mnt/ThumborMongoShardingCompose/nginxBalance:/etc/nginx/conf.d
    ports:
      - "8123:80"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - thumborapi
  thumbor1:
    image: lionants02/thumbormongodocker:1.3
    environment:
      - MONGO_STORAGE_SERVER_HOST=router1
      - MONGO_STORAGE_SERVER_PORT=27081
      - MONGO_STORAGE_SERVER_DB=picture
      - MONGO_STORAGE_SERVER_COLLECTION=imagefile
      - UPLOAD_ENABLED=True
      - UPLOAD_PUT_ALLOWED=True
      - UPLOAD_DELETE_ALLOWED=True
      - STORAGE_EXPIRATION_SECONDS=2592000
      - MAX_WIDTH=0
      - MAX_HEIGHT=0
      - UPLOAD_MAX_SIZE=0
      - MAX_AGE=0
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - thumborapi

  router1:
    image: mongo:3.4
    ports:
      - "27081:27081"
    volumes:
      - /mnt/db:/data/db
    command: sh -c 'su --command "mongos --configdb configserver/config1:27019 --port 27081"'
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - config1
      - shard1n1
    networks:
      - mongoIMG

  config1:
    image: mongo:3.4
    volumes:
      - /mnt/configdb:/data/configdb
    command: mongod --configsvr --smallfiles --replSet configserver --port 27019
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - mongoIMG

  shard1n1:
    image: mongo:3.4
    volumes:
      - /mnt/db:/data/db
    ports:
      - "8001:27020"
    command: mongod --noprealloc --replSet dataGroup1 --shardsvr --port 27020
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - mongoIMG
