version: '3.3'


networks:
  thumborapi:
    external: true

services:

  nginx:
    image: nginx:latest
    volumes:
       - /mnt/git/ThumborMongoShardingCompose/nginxBalance:/etc/nginx/conf.d
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - thumborapi
    depends_on:
      - thumbor1

  thumbor1:
    image: lionants02/thumbormongodocker:1.3
    environment:
      - MONGO_STORAGE_SERVER_HOST=10.226.49.110
      - MONGO_STORAGE_SERVER_PORT=27081
      - MONGO_STORAGE_SERVER_DB=picture
      - MONGO_STORAGE_SERVER_COLLECTION=imagefile
      - UPLOAD_ENABLED=True
      - UPLOAD_PUT_ALLOWED=True
      - UPLOAD_DELETE_ALLOWED=True
      - STORAGE_EXPIRATION_SECONDS=2592000
      - MAX_WIDTH=0
      - MAX_HEIGHT=0
      - UPLOAD_MAX_SIZE=0
      - MAX_AGE=0
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - thumborapi
