version: '3'
services:
  config1:
    image: mongo:3.4
    deploy:
      mode: global
    command: mongod --configsvr --dbpath /data/configdb --port 27019
    networks:
      -mongo1-network

  config2:
    image: mongo:3.4
    deploy:
      mode: global
    command: mongod --configsvr --dbpath /data/configdb --port 27019
    networks:
      -mongo1-network

  shard1:
    image: mongo:3.4
    deploy:
      mode: global
    networks:
      -mongo1-network

  shard2:
    image: mongo:3.4
    deploy:
      mode: global
    networks:
      -mongo1-network

  shard3:
    image: mongo:3.4
    deploy:
      mode: global
    networks:
      -mongo1-network

  router1:
    image: mongo:3.4
    deploy:
      mode: replicated
      replicas: 2
    command: mongos --configdb config1:27019 config2:27019 --port 27081
    ports:
    - "27081:27081"
    links:
      -config1
      -shard1
      -shard2
      -shard3
    networks:
      -mongo1-network

networks:
  mongo1-network
    driver: bridge
